config/routes.rb
Rails.application.routes.draw do
  resources :pemantauans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pemantauan.rb
# class Pemantauan < ApplicationRecord
# end


class Pemantauan < ActiveRecord::Base
  validates :kabupaten, length: { minimum: 5 }
  validates :tema, length: { in:10..1000 }
  validates :tanggal, length: { minimum: 6 }
  validates :jml_FM_FS, length: { minimum: 1 }
  validates :jml_peserta_FM_FS, length: { minimum: 1 }
  validates :peserta_roms_kab, length: { minimum: 1 }
  validates :notula, length: { minimum: 1 }
  validates :daftar_hadir, length: { minimum: 1 }
  validates :foto, length: { minimum: 1 }
end

# 	def self.to_csv
# 		CSV.generate do |variable|
# 			csv << column_names
# 			all.each do |post|
# end




# td><%= pemantauan.kabupaten %></td>
#         <td><%= pemantauan.misday_bulan %></td>
#         <td><%= pemantauan.tema %></td>
#         <td><%= pemantauan.tanggal %></td>
#         <td><%= pemantauan.jml_FM_FS %></td>
#         <td><%= pemantauan.jml_peserta_FM_FS %></td>
#         <td><%= pemantauan.peserta_roms_kab %></td>
#         <td><%= pemantauan.notula %></td>
#         <td><%= pemantauan.daftar_hadir %></td>
#         <td><%= pemantauan.foto %></td>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pemantauans_controller.rb
class PemantauansController < ApplicationController
  before_action :set_pemantauan, only: [:show, :edit, :update, :destroy]

  # GET /pemantauans
  # GET /pemantauans.json
  def index
    @pemantauans = Pemantauan.all
  end

  # GET /pemantauans/1
  # GET /pemantauans/1.json
  def show
  end

  # GET /pemantauans/new
  def new
    @pemantauan = Pemantauan.new
  end

  # GET /pemantauans/1/edit
  def edit
  end

  # POST /pemantauans
  # POST /pemantauans.json
  def create
    @pemantauan = Pemantauan.new(pemantauan_params)

    respond_to do |format|
      if @pemantauan.save
        format.html { redirect_to @pemantauan, notice: 'Pemantauan was successfully created.' }
        format.json { render :show, status: :created, location: @pemantauan }
      else
        format.html { render :new }
        format.json { render json: @pemantauan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pemantauans/1
  # PATCH/PUT /pemantauans/1.json
  def update
    respond_to do |format|
      if @pemantauan.update(pemantauan_params)
        format.html { redirect_to @pemantauan, notice: 'Pemantauan was successfully updated.' }
        format.json { render :show, status: :ok, location: @pemantauan }
      else
        format.html { render :edit }
        format.json { render json: @pemantauan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pemantauans/1
  # DELETE /pemantauans/1.json
  def destroy
    @pemantauan.destroy
    respond_to do |format|
      format.html { redirect_to pemantauans_url, notice: 'Pemantauan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pemantauan
      @pemantauan = Pemantauan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pemantauan_params
      params.require(:pemantauan).permit(:kabupaten, :misday_bulan, :tema, :tanggal, :jml_FM_FS, :jml_peserta_FM_FS, :peserta_roms_kab, :notula, :daftar_hadir, :foto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pemantauans_helper.rb
module PemantauansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Misday1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pemantauans/_form.html.erb
<%= form_with(model: pemantauan, local: true) do |form| %>
  <% if pemantauan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pemantauan.errors.count, "error") %> prohibited this pemantauan from being saved:</h2>

      <ul>
      <% pemantauan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kabupaten %>
    <%= form.text_field :kabupaten %>
  </div>

  <div class="field">
    <%= form.label :misday_bulan %>
    <%= form.text_field :misday_bulan %>
  </div>

  <div class="field">
    <%= form.label :tema %>
    <%= form.text_area :tema %>
  </div>

  <div class="field">
    <%= form.label :tanggal %>
    <%= form.date_select :tanggal %>
  </div>

  <div class="field">
    <%= form.label :jml_FM_FS %>
    <%= form.text_field :jml_FM_FS %>
  </div>

  <div class="field">
    <%= form.label :jml_peserta_FM_FS %>
    <%= form.text_field :jml_peserta_FM_FS %>
  </div>

  <div class="field">
    <%= form.label :peserta_roms_kab %>
    <%= form.text_field :peserta_roms_kab %>
  </div>

  <div class="field">
    <%= form.label :notula %>
    <%= form.text_field :notula %>
  </div>

  <div class="field">
    <%= form.label :daftar_hadir %>
    <%= form.text_field :daftar_hadir %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pemantauans/edit.html.erb
<h1>Editing Pemantauan</h1>

<%= render 'form', pemantauan: @pemantauan %>

<%= link_to 'Show', @pemantauan %> |
<%= link_to 'Back', pemantauans_path %>

app/views/pemantauans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pemantauan Kegiatan MISDAY</h1>

<table>
  <thead>
    <tr>
      <th>Kabupaten</th>
      <th>MISDAY bulan</th>
      <th>Tema</th>
      <th>Tanggal</th>
      <th>Jml FM & FS</th>
      <th>Peserta MISDAY FM & FS</th>
      <th>Peserta ROMS Kab.</th>
      <th>Notula</th>
      <th>Daftar hadir</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pemantauans.each do |pemantauan| %>
      <tr>
        <td><%= pemantauan.kabupaten %></td>
        <td><%= pemantauan.misday_bulan %></td>
        <td><%= pemantauan.tema %></td>
        <td><%= pemantauan.tanggal %></td>
        <td><%= pemantauan.jml_FM_FS %></td>
        <td><%= pemantauan.jml_peserta_FM_FS %></td>
        <td><%= pemantauan.peserta_roms_kab %></td>
        <td><%= pemantauan.notula %></td>
        <td><%= pemantauan.daftar_hadir %></td>
        <td><%= pemantauan.foto %></td>
        <td><%= link_to 'Show', pemantauan %></td>
        <td><%= link_to 'Edit', edit_pemantauan_path(pemantauan) %></td>
       <!--  <td><%= link_to 'Destroy', pemantauan, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pemantauan', new_pemantauan_path %>


<h4>Keterangan:</h4>
<ul>
  <li>MISDAY bulan: adalah bulan di lakukan MISDAY tersebut</li>
  <li>Tanggal: Tanggal, bulan dan tahun dilakukannya MISDAY tersebut</li>
  <li>Jumlah FM FS: adalah jumlah total FM dan FS yang ada di Kabupaten</li>
  <li>Peserta FM FS: adalah FS dan FM yang hadir dalam event MIS DAY </li>
  <li>ROMS Kab.: adalah anggota ROMS Kabupaten yang hadir dalam event MIS DAY</li>
  <li>Notula: Jika ada notula di isi angka 1, jika tidak diisi angka 0</li>
  <li>Daftar Hadir: Jika ada daftar hadir di isi angka 1, jika tidak diisi angka 0  </li>
  <li>Foto: Jika ada foto di isi angka 1, jika tidak diisi angka 0</li>
</ul>

app/views/pemantauans/new.html.erb
<h1>New Pemantauan</h1>

<%= render 'form', pemantauan: @pemantauan %>

<%= link_to 'Back', pemantauans_path %>

app/views/pemantauans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kabupaten:</strong>
  <%= @pemantauan.kabupaten %>
</p>

<p>
  <strong>Misday bulan:</strong>
  <%= @pemantauan.misday_bulan %>
</p>

<p>
  <strong>Tema:</strong>
  <%= @pemantauan.tema %>
</p>

<p>
  <strong>Tanggal:</strong>
  <%= @pemantauan.tanggal %>
</p>

<p>
  <strong>Jml fm fs:</strong>
  <%= @pemantauan.jml_FM_FS %>
</p>

<p>
  <strong>Jml peserta fm fs:</strong>
  <%= @pemantauan.jml_peserta_FM_FS %>
</p>

<p>
  <strong>Peserta roms kab:</strong>
  <%= @pemantauan.peserta_roms_kab %>
</p>

<p>
  <strong>Notula:</strong>
  <%= @pemantauan.notula %>
</p>

<p>
  <strong>Daftar hadir:</strong>
  <%= @pemantauan.daftar_hadir %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @pemantauan.foto %>
</p>

<%= link_to 'Edit', edit_pemantauan_path(@pemantauan) %> |
<%= link_to 'Back', pemantauans_path %>